In [230]:
# Load Libraries

import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.covariance import MinCovDet
from scipy.stats.mstats import mquantiles

In [231]:
# Load Data

GTD = pd.read_csv('C:/R Portfolio/Global_Terrorism_Prediction/globalterrorismdb_0522dist.csv', 
                     encoding = 'latin1',
                     low_memory = False)
GTD_1 = pd.read_csv('C:/R Portfolio/Global_Terrorism_Prediction/globalterrorismdb_2021Jan-June_1222dist.csv', 
                     encoding = 'latin1',
                     low_memory = False)
GTD_combined = pd.concat([GTD, GTD_1], ignore_index = True)
GTD_combined

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214661,202106300023,2021,6,30,NaN,0,NaN,4,Afghanistan,6,...,NaN,"""Gunmen blow up power pylon in Parwan,"" Afghan...","""Provinces hit by blackout after power pylon d...",NaN,START Primary Collection,-9,-9,0,-9,NaN
214662,202106300029,2021,6,30,06/30/2021,0,NaN,138,Myanmar,5,...,NaN,"""Spring Revolution Daily News for 16-30 June 2...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
214663,202106300030,2021,6,30,NaN,1,08/07/2021,147,Nigeria,11,...,NaN,"""Boko Haram Releases Abducted Catholic Priest ...","""Kidnapped Maiduguri Catholic Priest regains f...","""ISWAP-Boko Haram Abduct Catholic Priest In Bo...",START Primary Collection,0,0,0,0,NaN
214664,202106300038,2021,6,30,NaN,0,NaN,45,Colombia,3,...,NaN,"""Two dead and one wounded after clashes betwee...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
214665,202107020037,2021,6,30,NaN,0,NaN,138,Myanmar,5,...,There is doubt that this incident meets terror...,"""Spring Revolution Daily News for 2-7 July 202...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN

In [232]:
# Load Functions

execfile('C:/Python_Data_Sets/Functions 10_07_2023.py')

In [233]:
# Process Data

GTD_New = preprocess_data(GTD_combined)
GTD_New

,Year,Month,Day,Country,Region,Province,City,Attack,Target,Group,Weapon,Dead,Lethal
0,1970,7,2,OtherCountry,Central America & Caribbean,OtherProvince,OtherCity,Assassination,Private,OtherGroup,OtherWeapon,1.0,1
1,1970,0,0,OtherCountry,North America,OtherProvince,OtherCity,HostageKidnapAttack,OtherTarget,OtherGroup,OtherWeapon,0.0,0
2,1970,1,0,OtherCountry,Southeast Asia,OtherProvince,Unknown,Assassination,OtherTarget,OtherGroup,OtherWeapon,1.0,1
3,1970,1,0,OtherCountry,Western Europe,OtherProvince,OtherCity,BombAttack,OtherTarget,OtherGroup,Explosives,0.0,0
4,1970,1,0,OtherCountry,East Asia,OtherProvince,OtherCity,InfrastructureAttack,OtherTarget,OtherGroup,Incendiary,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
214661,2021,6,30,Afghanistan,South Asia,OtherProvince,OtherCity,BombAttack,OtherTarget,OtherGroup,Explosives,0.0,0
214662,2021,6,30,OtherCountry,Southeast Asia,OtherProvince,OtherCity,HostageKidnapAttack,OtherTarget,OtherGroup,OtherWeapon,1.0,1
214663,2021,6,30,OtherCountry,Sub-Saharan Africa,OtherProvince,Unknown,HostageKidnapAttack,OtherTarget,OtherGroup,Firearms,0.0,0
214664,2021,6,30,OtherCountry,South America,OtherProvince,Unknown,BombAttack,OtherTarget,OtherGroup,Explosives,0.0,0
214665,2021,6,30,OtherCountry,Southeast Asia,OtherProvince,OtherCity,BombAttack,Business,OtherGroup,Explosives,0.0,0

In [234]:
# Region Data

# EE Region Data
EE_data = GTD_New[GTD_New['Region'] == 'Eastern Europe']
EE_data

,Year,Month,Day,Country,Region,Province,City,Attack,Target,Group,Weapon,Dead,Lethal
15,1970,1,10,OtherCountry,Eastern Europe,OtherProvince,OtherCity,BombAttack,GovtGen,OtherGroup,Explosives,0.0,0
34,1970,1,28,OtherCountry,Eastern Europe,OtherProvince,OtherCity,InfrastructureAttack,Police,OtherGroup,Incendiary,0.0,0
241,1970,4,28,OtherCountry,Eastern Europe,OtherProvince,OtherCity,InfrastructureAttack,GovtGen,OtherGroup,Incendiary,0.0,0
258,1970,5,5,OtherCountry,Eastern Europe,OtherProvince,OtherCity,InfrastructureAttack,OtherTarget,OtherGroup,Incendiary,0.0,0
275,1970,5,10,OtherCountry,Eastern Europe,OtherProvince,OtherCity,InfrastructureAttack,Business,OtherGroup,Incendiary,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
213322,2021,5,4,OtherCountry,Eastern Europe,OtherProvince,OtherCity,BombAttack,Business,OtherGroup,Explosives,0.0,0
213341,2021,5,5,OtherCountry,Eastern Europe,OtherProvince,OtherCity,BombAttack,Private,OtherGroup,Explosives,0.0,0
213775,2021,5,25,OtherCountry,Eastern Europe,OtherProvince,OtherCity,BombAttack,Private,OtherGroup,Explosives,0.0,0
213813,2021,5,27,OtherCountry,Eastern Europe,OtherProvince,OtherCity,ArmedAssaultAttack,Military,OtherGroup,Explosives,1.0,1
214312,2021,6,17,OtherCountry,Eastern Europe,OtherProvince,OtherCity,InfrastructureAttack,OtherTarget,OtherGroup,Incendiary,0.0,0

In [235]:
# Drop the specified columns
columns_to_drop = ['Month', 'Day', 'Region']
EE_data_2 = EE_data.drop(columns = columns_to_drop)
# Convert the 'Category' column to categorical type
EE_data_2['Country'] = EE_data_2['Country'].astype('category')
# Convert Data into Dummy format

EE_categorical_cols = ['Country', 'Province', 'City', 'Attack', 'Target', 'Group', 'Weapon']
EE_data_2 = pd.get_dummies(EE_data_2, columns = EE_categorical_cols)
# Remove "Attack_" and "Target_" from column names
EE_data_2.columns = EE_data_2.columns.str.replace('Attack_', '').str.replace('Target_', '').str.replace('Weapon_', '').str.replace('Country_', '').str.replace('Province_', '').str.replace('City_', '')
EE_data_2

,Year,Dead,Lethal,OtherCountry,OtherProvince,OtherCity,Unknown,ArmedAssaultAttack,Assassination,BombAttack,...,GovtGen,Military,OtherTarget,Police,Private,Group_OtherGroup,Explosives,Firearms,Incendiary,OtherWeapon
15,1970,0.0,0,1,1,1,0,0,0,1,...,1,0,0,0,0,1,1,0,0,0
34,1970,0.0,0,1,1,1,0,0,0,0,...,0,0,0,1,0,1,0,0,1,0
241,1970,0.0,0,1,1,1,0,0,0,0,...,1,0,0,0,0,1,0,0,1,0
258,1970,0.0,0,1,1,1,0,0,0,0,...,0,0,1,0,0,1,0,0,1,0
275,1970,0.0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213322,2021,0.0,0,1,1,1,0,0,0,1,...,0,0,0,0,0,1,1,0,0,0
213341,2021,0.0,0,1,1,1,0,0,0,1,...,0,0,0,0,1,1,1,0,0,0
213775,2021,0.0,0,1,1,1,0,0,0,1,...,0,0,0,0,1,1,1,0,0,0
213813,2021,1.0,1,1,1,1,0,1,0,0,...,0,1,0,0,0,1,1,0,0,0
214312,2021,0.0,0,1,1,1,0,0,0,0,...,0,0,1,0,0,1,0,0,1,0

In [236]:
EE_data_3 = EE_data_2.groupby(['Year'])[['Dead',
        'Lethal',
        'OtherCountry',
        'OtherProvince',
        'OtherCity',
        'Unknown',
        'ArmedAssaultAttack',
        'Assassination',
        'BombAttack',
        'HostageKidnapAttack',
        'InfrastructureAttack',
        'OtherAttack',
        'Business',
        'GovtGen',
        'Military',
        'OtherTarget',
        'Police',
        'Private',
        'Group_OtherGroup',
        'Explosives',
        'Firearms',
        'Incendiary',
        'OtherWeapon']].sum()
EE_data_3

,Dead,Lethal,OtherCountry,OtherProvince,OtherCity,Unknown,Unknown,ArmedAssaultAttack,Assassination,BombAttack,...,GovtGen,Military,OtherTarget,Police,Private,Group_OtherGroup,Explosives,Firearms,Incendiary,OtherWeapon
Year,,,,,,,,,,,,,,,,,,,,,
1970,0.0,0,12,12,12,0,0,0,0,8,...,3,0,3,3,1,12,8,0,4,0
1971,0.0,0,5,5,5,0,0,0,0,1,...,0,0,1,4,0,5,1,0,4,0
1972,26.0,1,1,1,0,1,0,0,0,1,...,0,0,1,0,0,1,1,0,0,0
1973,1.0,1,1,1,1,0,0,0,0,1,...,0,0,1,0,0,1,1,0,0,0
1974,1.0,1,2,2,2,0,0,0,0,1,...,1,0,1,0,0,2,1,0,0,1
1977,1.0,1,2,2,2,0,0,1,0,1,...,0,0,1,0,0,2,1,1,0,0
1978,4.0,1,2,2,2,0,0,0,1,1,...,0,0,2,0,0,2,1,1,0,0
1979,0.0,0,1,1,1,0,0,0,0,1,...,0,0,0,0,1,1,1,0,0,0
1980,0.0,0,1,1,1,0,0,0,0,1,...,0,0,1,0,0,1,1,0,0,0
1981,0.0,0,4,4,4,0,0,0,1,2,...,0,1,3,0,0,4,2,1,0,1
1982,2.0,2,3,3,3,0,0,0,2,1,...,0,0,3,0,0,3,1,2,0,0
1983,2.0,1,2,2,2,0,0,0,1,1,...,0,1,1,0,0,2,1,1,0,0
1984,3.0,2,4,4,4,0,1,0,2,1,...,0,0,2,1,1,4,1,2,0,1
1985,2.0,1,5,5,5,0,0,0,0,5,...,0,0,1,1,1,5,5,0,0,0
1986,1.0,1,3,3,3,0,0,0,2,1,...,0,1,2,0,0,3,1,1,0,1
1987,0.0,0,1,1,1,0,0,0,1,0,...,1,0,0,0,0,1,0,1,0,0
1988,0.0,0,4,4,4,0,0,0,0,0,...,0,1,0,0,0,4,0,0,4,0
1989,6.0,2,16,16,16,0,0,1,0,13,...,1,1,10,0,3,16,12,2,1,1
1990,59.0,17,58,58,56,2,1,16,7,27,...,7,6,20,7,14,58,27,24,6,1
1991,273.0,23,84,84,82,2,3,27,7,38,...,16,7,22,24,13,84,36,39,2,7
1992,110.0,31,91,91,90,1,4,27,10,40,...,13,10,40,13,9,91,41,37,1,12
1994,49.0,28,95,95,89,6,3,8,27,48,...,24,6,35,4,12,95,54,25,0,16
1995,158.0,27,68,68,68,0,1,7,19,32,...,16,2,27,5,5,68,35,20,2,11
1996,167.0,51,175,175,173,2,3,17,35,109,...,32,5,60,18,25,175,113,45,3,14
1997,115.0,64,248,248,234,14,3,46,31,125,...,45,12,73,34,45,248,128,77,8,35
1998,109.0,32,105,105,104,1,1,34,7,51,...,19,9,22,30,13,105,57,41,3,4
1999,440.0,44,138,138,134,4,5,35,11,67,...,22,20,35,9,36,138,73,47,9,9
2000,402.0,107,234,234,231,3,3,61,17,142,...,49,50,35,22,62,234,147,74,4,9
2001,294.0,101,252,252,250,2,5,70,19,122,...,42,24,49,84,40,252,130,95,5,22
2002,518.0,59,112,112,112,0,2,22,11,68,...,17,42,13,19,14,112,68,37,3,4
2003,337.0,49,100,100,99,1,1,18,9,60,...,28,19,22,18,8,100,63,28,3,6
2004,584.0,25,45,45,45,0,1,5,7,25,...,9,5,16,6,3,45,32,7,3,3
2005,158.0,35,76,76,75,1,0,22,7,46,...,17,6,17,25,5,76,50,24,1,1
2006,59.0,24,70,70,69,1,2,13,1,39,...,5,5,15,14,25,70,39,15,1,15
2007,57.0,28,62,62,62,0,1,33,2,22,...,7,6,7,32,6,62,23,35,1,3
2008,101.0,57,209,209,208,0,1,68,14,111,...,44,2,29,58,53,209,115,77,11,6
2009,143.0,67,165,165,165,0,0,49,17,89,...,41,2,46,38,27,165,93,66,2,4
2010,235.0,100,261,261,261,0,0,63,31,152,...,46,3,60,88,38,261,162,83,13,3
2011,174.0,78,198,198,193,1,1,61,21,110,...,34,1,43,60,30,198,116,77,2,3
2012,179.0,74,173,173,168,5,1,50,14,104,...,20,16,40,63,18,173,117,51,0,5
2013,151.0,71,166,166,158,8,1,44,14,91,...,19,9,49,65,10,166,96,56,8,6
2014,1468.0,244,963,963,922,41,49,270,15,454,...,64,495,145,64,149,963,550,249,22,142
2015,791.0,159,685,685,671,14,18,158,12,456,...,22,347,105,24,148,685,566,62,25,32
2016,112.0,38,136,136,131,5,2,33,13,55,...,19,11,53,30,16,136,67,38,18,13
2017,101.0,34,112,112,109,3,2,18,14,43,...,13,11,34,14,31,112,52,24,19,17
2018,41.0,20,72,72,69,3,1,15,8,20,...,9,3,23,7,27,72,22,17,17,16
2019,34.0,17,44,44,39,5,1,7,6,17,...,9,8,11,3,10,44,19,7,8,10
2020,15.0,12,60,60,59,1,0,10,2,23,...,5,12,25,4,10,60,29,4,22,5
2021,8.0,5,16,16,16,0,0,4,1,5,...,0,3,8,0,4,16,8,0,5,3

In [238]:
# Replace the sample data with your actual data
EE_data_3 = np.array(EE_data_3)

# Remove NaN values from the NumPy array
EE_data_3 = EE_data_3[~np.isnan(EE_data_3).any(axis=1)]
EE_data_3

array([[ 0.,  0., 12., ...,  0.,  4.,  0.],
       [ 0.,  0.,  5., ...,  0.,  4.,  0.],
       [26.,  1.,  1., ...,  0.,  0.,  0.],
       ...,
       [34., 17., 44., ...,  7.,  8., 10.],
       [15., 12., 60., ...,  4., 22.,  5.],
       [ 8.,  5., 16., ...,  0.,  5.,  3.]])

In [239]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.covariance import MinCovDet

def perform_outlier_analysis(data, remove_outliers=False):
    data = np.array(data)

    # Remove NaN values from the NumPy array
    data = data[~np.isnan(data).any(axis=1)]

    outliers_dist = []
    outliers_pca = []

    # Calculate robust Mahalanobis distance
    robust_cov = MinCovDet().fit(data)
    robust_dist = robust_cov.mahalanobis(data)
    quantile_value = np.percentile(robust_dist, 95)
    outliers_indices_dist = np.where(robust_dist > quantile_value)
    outliers_indices_dist = np.unique(outliers_indices_dist[0])
    outliers_dist = data[outliers_indices_dist]

    # Calculate robust PCA
    robust_pca = PCA()
    robust_pca.components_ = robust_cov.location_
    residuals = np.zeros_like(data)
    for i in range(data.shape[0]):
        residuals[i] = data[i] - np.dot(np.dot(data[i], robust_pca.components_.T), robust_pca.components_)
    residuals_pca = np.zeros_like(data)
    for i in range(data.shape[0]):
        residuals_pca[i] = residuals[i] - np.dot(np.dot(residuals[i], robust_pca.components_.T), robust_pca.components_)
    robust_cov_pca = MinCovDet().fit(residuals_pca)
    robust_pca.components_ = robust_cov_pca.location_
    residuals_pca = np.zeros_like(data)
    for i in range(data.shape[0]):
        residuals_pca[i] = residuals[i] - np.dot(np.dot(residuals[i], robust_pca.components_.T), robust_pca.components_)
    robust_dist_pca = robust_cov_pca.mahalanobis(residuals_pca)
    quantile_value_pca = np.percentile(robust_dist_pca, 95)
    outliers_indices_pca = np.where(robust_dist_pca > quantile_value_pca)
    outliers_indices_pca = np.unique(outliers_indices_pca[0])
    outliers_pca = data[outliers_indices_pca]

    # Combine outliers from both methods
    all_outliers = np.concatenate((outliers_dist, outliers_pca), axis=0)
    unique_outliers = np.unique(all_outliers, axis=0)

    if remove_outliers:
        data = np.array([row for row in data if row not in unique_outliers])

    return outliers_dist, outliers_pca, unique_outliers, data

In [240]:
# Replace the sample data with your actual data
EE_data_3 = np.array(EE_data_3)

# Perform outlier analysis
outliers_dist, outliers_pca, combined_outliers, data_without_outliers = perform_outlier_analysis(EE_data_3, remove_outliers=False)

C:\Users\Nicholas\anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:738: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn(
C:\Users\Nicholas\anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:738: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn(

In [241]:
# Print the outliers based on robust Mahalanobis distance
print("Outliers based on Mahalanobis distance:")
for outlier in outliers_dist:
    print(outlier)

Outliers based on Mahalanobis distance:
[115.  64. 248. 248. 234.  14.   3.  46.  31. 125.  33.   5.   5.  39.
  45.  12.  73.  34.  45. 248. 128.  77.   8.  35.]
[1468.  244.  963.  963.  922.   41.   49.  270.   15.  454.   94.   66.
   15.   46.   64.  495.  145.   64.  149.  963.  550.  249.   22.  142.]
[791. 159. 685. 685. 671.  14.  18. 158.  12. 456.  13.  26.   2.  39.
  22. 347. 105.  24. 148. 685. 566.  62.  25.  32.]

In [242]:
# Print the outliers based on robust PCA
print("Outliers based on PCA:")
for outlier in outliers_pca:
    print(outlier)

Outliers based on PCA:
[402. 107. 234. 234. 231.   3.   3.  61.  17. 142.   2.   6.   3.  16.
  49.  50.  35.  22.  62. 234. 147.  74.   4.   9.]
[1468.  244.  963.  963.  922.   41.   49.  270.   15.  454.   94.   66.
   15.   46.   64.  495.  145.   64.  149.  963.  550.  249.   22.  142.]
[791. 159. 685. 685. 671.  14.  18. 158.  12. 456.  13.  26.   2.  39.
  22. 347. 105.  24. 148. 685. 566.  62.  25.  32.]

In [243]:
# Print the combined list of outliers
print("Combined outliers:")
for outlier in combined_outliers:
    print(outlier)

Combined outliers:
[115.  64. 248. 248. 234.  14.   3.  46.  31. 125.  33.   5.   5.  39.
  45.  12.  73.  34.  45. 248. 128.  77.   8.  35.]
[402. 107. 234. 234. 231.   3.   3.  61.  17. 142.   2.   6.   3.  16.
  49.  50.  35.  22.  62. 234. 147.  74.   4.   9.]
[791. 159. 685. 685. 671.  14.  18. 158.  12. 456.  13.  26.   2.  39.
  22. 347. 105.  24. 148. 685. 566.  62.  25.  32.]
[1468.  244.  963.  963.  922.   41.   49.  270.   15.  454.   94.   66.
   15.   46.   64.  495.  145.   64.  149.  963.  550.  249.   22.  142.]